#pragma once
#include "Objects.hpp"
#include "Map.hpp"
#include "FastNoiseLite.h"
namespace kk{
    /**
     * Class for adding details to already generated map
     */
    class MapDetails{
    private:
        int m_seed; ///< seed for details layer generated by Perlin noise generator
        float m_frequency = 0.2f; ///< frequency for details layer
        /**
         * Function for creating details layer using Perlin noise 
         * @param layer reference to map
         */
        void CreateDetailLayer(Map& layer);

        /**
         * Function applying biome related details to map based on noise value
         * @param layer reference to map
         */
        void BiomeDetails(Map& layer);

        /**
         * Function for placing objects on map based on biome dependencies and noise value
         * @param layer reference to map 
         */
        void ObjectPlacer(Map& layer);
    public:
        /**
         * Parametrized constructor allowing for seed change but keeping default frequency
         * @param seed Perlin noise seed
         */
        MapDetails(int seed);

        /**
         * Parametrized constructor allowing to change both seed and frequency
         * @param seed Perlin noise seed
         * @param frequency frequency for Perlin noise
         */
        MapDetails(int seed, float freq);

        /**
         * Function for calling other functions in strict order
         * @param finishedMap Map that details will be applied to 
         */
        void ApplyDetails(Map& finishedMap); 

        /**
         * Function for setting seed value
         * @param seed value of seed
         */
        void setSeed(int seed);

        /**
         * Function for setting frequency 
         * @param freq value of frequency ()
         */
        void setFrequency(float freq);
    };
}